### ISSUE TITLE
Process map fails if event log contains "Start" or "End" activity

### ISSUE THREAD

**Issue by gertjanssenswillen** [bupaverse/processmapR#12]
Silently remove or give a warning?
Perhaps the events can be used to show a duration on the incoming/outgoing arcs.

**Comment by fmannhardt** [comment]
I think silently removing sounds like a bad idea and warning would be reasonable. Should be easy for people to rename their activities. 

Maybe the combination of a warning and special treatment for showing durations on the arcs would be best. Something like "Be aware that we expect that "Start" and "End" activities occur only once each trace and at the start/end of it."

**Comment by gertjanssenswillen** [comment]
Jep, I only realised after writing this that existing start and end activities do not necessarily occur where we expect them. Another solution would just be the use another underlying id for the start/end points we create, thus avoid conflict.

**Comment by gertjanssenswillen** [comment]
Issue fixed. Start and End will now just be treated as regular activities if they occur in the log. The start and end points of the process map use a different label underneath (which is less probable to be seen in the wild)
