### ISSUE TITLE
type relative_case problem in process_map

### ISSUE THREAD

**Issue by trikiamine23** [bupaverse/processmapR#29]
Hello,

I was wondering why would I have a slight (some time questionable) differences between type=frequency("relative_case") or type_node=frequency("relative_case").
I get different labels for nodes.
this is an example:

with type:
 
![image](https://user-images.githubusercontent.com/56306832/89168971-e7836e00-d57d-11ea-8b58-fae662630d01.png)

with type_node:

![image](https://user-images.githubusercontent.com/56306832/89169182-2fa29080-d57e-11ea-96cd-e36e7a057b70.png)

PS: the relative_case in type_node is used with performance in edges

Thank you in advance

**Comment by gertjanssenswillen** [comment]
Should not be happening, so I expect it is a small bug somewhere. Will look into it.

**Comment by trikiamine23** [comment]
my bad, the difference is the filter I add to the second format, it changes everything.
I closed the issue.

Thank you anyway
