### ISSUE TITLE
Start / End Inserts

### ISSUE THREAD

**Issue by aiteammember** [bupaverse/processmapR#32]
When you enable sec_nodes, it changes the word "Start" to "Artificial_Start" and "End" to "Artificial_End" .  Any way to make this configurable or change it to "Start" like all of the methods?

sec_nodes = frequency("relative-case")

**Comment by gertjanssenswillen** [comment]
Thx for noticing, this is obviously a bug. 

Can you show the full process_map call you are using? So far, I cannot seem to reproduce it. Thx

**Comment by gertjanssenswillen** [comment]
I have reproduced the problem by now, fix will follow.
