### ISSUE TITLE
Error while running function process_map( )

### ISSUE THREAD

**Issue by RahulEcon** [bupaverse/processmapR#34]
I get the following error on my plot viewer when running my event log object in process_map( ):
`Error: syntax error in line 33650 near '['`
I'm a bit new to the package, so please excuse me if I'm overstepping here. Thank you.

**Comment by gertjanssenswillen** [comment]
You closed the issue, does that mean it is solved?

What could be a problem is the presence of certain characters in the activity names (symbols or "). Removing these might solve the problem.
