### ISSUE TITLE
Precedence Matrix Plot Error

### ISSUE THREAD

**Issue by logLoss** [bupaverse/processmapR#47]
Plotting the Precedence matrix, suddenly gives an error. It did not use to do it before. It is either a recent change or dependency change.

_Error in count_precedence(simplelog$case_id, simplelog$activity_id, lead) : 
  Not compatible with requested type: [type=character; target=integer]._

Simple code:

wrk.log %>%
  precedence_matrix(type = "relative-antecedent") %>%
  plot

**Comment by gertjanssenswillen** [comment]
Packages are currently being updated. Can you tell me which version of bupaR and processmapR you are using? And what is the str of wrk.log? (espec. the types of activity and case_id)

**Comment by logLoss** [comment]
bupaR 0.5.0
processmapR 0.3.5


eventlog [12,559 × 7] (S3: eventlog/log/tbl_df/tbl/data.frame)
 $ CaseID          : chr [1:12559] "request0" "request0" "request0" "request1" ...
 $ Activity        : chr [1:12559] "REPORTED" "WAPPR" "APPR" "REPORTED" ...
 $ ActivityInstance: int [1:12559] 1 2 3 4 5 6 7 8 9 10 ...
 $ Status          : chr [1:12559] "Complete" "Complete" "Complete" "Complete" ...
 $ Timestamp       : POSIXct[1:12559], format: "2021-01-01 11:35:17" "2021-01-01 11:38:16" "2021-01-01 11:41:31" ...
 $ resource        : chr [1:12559] "Worker" "Admin" "Supervisor" "Worker" ...
 $ .order          : int [1:12559] 1 2 3 4 5 6 7 8 9 10 ...
 - attr(*, "case_id")= chr "CaseID"
 - attr(*, "activity_id")= chr "Activity"
 - attr(*, "activity_instance_id")= chr "ActivityInstance"
 - attr(*, "lifecycle_id")= chr "Status"
 - attr(*, "resource_id")= chr "resource"
 - attr(*, "timestamp")= chr "Timestamp"

**Comment by gertjanssenswillen** [comment]
Try updating processmapR to 0.5.0 (was released yesterday). Let me know if that helps or not.

**Comment by logLoss** [comment]
I have installed processmapR 0.5.0 and still get the same error.

other attached packages:
 [1] processanimateR_1.0.4 xesreadR_0.2.3        processmapR_0.5.0    
 [4] eventdataR_0.3.1      edeaR_0.9.0           bupaR_0.5.0          
 [7] simmer_4.4.5          forcats_0.5.1         stringr_1.4.0        
[10] dplyr_1.0.9           purrr_0.3.4           tidyr_1.2.0          
[13] tibble_3.1.7          ggplot2_3.3.6         tidyverse_1.3.1      
[16] readr_2.1.2

**Comment by logLoss** [comment]
When I try the new function it works:

wrk.log %>%
  process_matrix(type = frequency()) %>%
  plot

**Comment by gertjanssenswillen** [comment]
Some changes have been pushed to github. 
- I was able to reproduce and fix the error in the precendence_matrix function
- I have added functionality to process_matrix for it to be a valid replacement of the deprecated function (it didn't allow for the relative-antecedent option)

Fixes should appear later this week on CRAN as well.
