### ISSUE TITLE
Label incorrect in process_map (weight)

### ISSUE THREAD

**Issue by th72** [bupaverse/processmapR#57]
Hi,

Strange issue with labeling in process_map. The word: "weight" is inside the label and the label is truncated.

I tried development versions.... but the problem stayed. I run Mac M2 and R version 4.3

<img width="342" alt="incorrect_label" src="https://github.com/bupaverse/processmapR/assets/47389631/9c5d5afb-8406-4c8f-9d19-02a8476fe9d8">

**Comment by gertjanssenswillen** [comment]
Known issue, I'll try to fix asap. 
WIth truncated: do you mean where weight is inserted, or is there also something truncated at the end?

**Comment by th72** [comment]
Thanks for looking into this issue :-) "weight" is inserted after 7/8 characters.... 

original: Beoordelen PNIL indienst
bug: Beoordeweight PNIL indienst

original: Route bepalen
bug: Route bepaweight

**Comment by gertjanssenswillen** [comment]
Problem should now be solved, using the version on github.

**Comment by th72** [comment]
Yes, bug is fixed. Thanks!

<img width="217" alt="bug fixed" src="https://github.com/bupaverse/processmapR/assets/47389631/af3f9496-39f2-468a-8323-5a920520357e">
