### ISSUE TITLE
Metadata from Process Maps? Potential Enhancement

### ISSUE THREAD

**Issue by crarnouts** [bupaverse/processmapR#9]
Hey so this is not an issue but rather a potential enhancement or feature, my hope is to find a way to grab the actual metadata from the process maps themselves. Like the metrics that are generated on the nodes and the edges

![image](https://user-images.githubusercontent.com/41031719/71678146-7a42fc80-2d52-11ea-858f-f4686570d05d.png)

In the image above I would like to be able to grab the metrics from the edges so from the contact - Other to the Investigation activity  I would grab the .17. 

I am hoping to use these as predictive features.

I could do this in sort of a manual way but I figured the meta data is already being created

**Comment by fmannhardt** [comment]
The process map already has the data of the process map attached to the returned object as attribute called `base_precedence`. This is so far undocumented, so may change in the future. But I am making use of that in `processanimateR` to avoid recalculating all the information.

You can see it in use here:
https://github.com/bupaverse/processanimateR/blob/273fcc97850e16b63c2cfdf7b13b30d12869e97d/R/processanimateR.R#L114

**Comment by gertjanssenswillen** [comment]
You could compute the aggregated data separately using process_matrix. This supports the same frequency() and performance() functions as process_map, but gives you a list of the edges and the required data

`
patients %>% process_matrix(frequency("relative"))
`
You could also work from the process map if you have it already, as @fmannhardt suggests. In that case we need indeed to clean up the output a bit and add some documentation. If you need the process map anyhow, that would be a more efficient way. I'll have a look at this option later this week.

**Comment by gertjanssenswillen** [comment]
Two new functions were create: get_activities(process_map) and get_flows(process_map), to extract the values of activities and flows from a process_map. Documentation will follow.
